import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'


function useIsFirstRender(): boolean {
  const isFirst = useRef(true)

  if (isFirst.current) {
    isFirst.current = false

    return true
  }

  return isFirst.current
}


export default function Home() {
  const isFirstRender = useIsFirstRender();

  const [didFetchData, setDidFetchData] = useState(false)

  const toggleDidFetchData = () => {
    setDidFetchData(current => !current);
  };


  useEffect(() => {
    if (isFirstRender) {
      console.log("This is the first render")
      return;
    }

    console.log("This is not the first render")
  }, [isFirstRender]);



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            This is very fast.
          </p>
        </div>
        <div>{didFetchData ? "Fetched" : "We should fetch data"}</div>
                <button onClick={toggleDidFetchData}>Fetch</button>
         <div>Did we fetch the data?: {didFetchData ? "Yes" : "No"}</div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
      </main>
    </>
  )
}
